### PR TITLE
Update Pydoop-related docs

### PR DESCRIPTION
**Pull request by simleo**
- Fix link to the Pydoop installation docs
- Update Pydoop installation instructions

### CODE REVIEW

**Comment by mkobos** [comment]
I tried to install Pydoop without installing the `libboost-python-dev`, `python-support`, `python-software-properties` packages first, just as you wrote in your pull request. Unfortunately, I got the error message shown below while executing `sudo -i pip install pydoop` (I tried it on a clean Ubuntu 14.04 system). The installation process went fine after installing these missing packages. It seems that they are required after all.

```
adminuser@adminuser-VirtualBox:~/tmp$ sudo -i pip install pydoop
Downloading/unpacking pydoop
  Downloading pydoop-0.12.0.tar.gz (1.2MB): 1.2MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pydoop/setup.py) egg_info for package pydoop

    *** WARNING: hadoop-2.0.0-cdh4.7.0 NOT SUPPORTED, TRYING hadoop-2.0.0-cdh4.3.0 ***
    patching source code 'src/hadoop-2.0.0-cdh4.7.0'
    patching file org/apache/hadoop/mapred/pipes/Application.java
    patching file pipes/impl/HadoopPipes.cc
    patching file utils/impl/SerialUtils.cc
    *** WARNING: hadoop-2.0.0-mr1-cdh4.7.0 NOT SUPPORTED, TRYING hadoop-2.0.0-mr1-cdh4.3.0 ***
    patching source code 'src/hadoop-2.0.0-mr1-cdh4.7.0'
    patching file libhdfs/hdfsJniHelper.c
    patching file org/apache/hadoop/mapred/pipes/Application.java
    patching file pipes/impl/HadoopPipes.cc
    patching file utils/impl/SerialUtils.cc
    java_include_dirs: ['/usr/lib/jvm/default-java/include', '/usr/lib/jvm/default-java/include/linux']
    java_library_dirs: ['/usr/lib/jvm/default-java/jre/lib/amd64/server']
    java_include_dirs: ['/usr/lib/jvm/default-java/include', '/usr/lib/jvm/default-java/include/linux']
    java_library_dirs: ['/usr/lib/jvm/default-java/jre/lib/amd64/server']
Installing collected packages: pydoop
  Running setup.py install for pydoop
    java_include_dirs: ['/usr/lib/jvm/default-java/include', '/usr/lib/jvm/default-java/include/linux']
    java_library_dirs: ['/usr/lib/jvm/default-java/jre/lib/amd64/server']
    java_include_dirs: ['/usr/lib/jvm/default-java/include', '/usr/lib/jvm/default-java/include/linux']
    java_library_dirs: ['/usr/lib/jvm/default-java/jre/lib/amd64/server']
    hadoop_home: '/usr/lib/hadoop'
    hadoop_version: '2.0.0-cdh4.7.0'
    java_home: '/usr/lib/jvm/default-java'
    building 'pydoop._pipes_2_0_0_cdh_4_7_0' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -Isrc/hadoop-2.0.0-cdh4.7.0.patched/pipes/api -Isrc/hadoop-2.0.0-cdh4.7.0.patched/utils/api -I/usr/include/python2.7 -c src/pipes.cpp -o build/temp.linux-x86_64-2.7/src/pipes.o
    In file included from src/pipes.hpp:30:0,
                     from src/pipes.cpp:21:
    src/pipes_context.hpp:33:28: fatal error: boost/python.hpp: No such file or directory
     #include <boost/python.hpp>
                                ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by simleo** [comment]
You're trying to install Pydoop 0.12. **That** version requires Boost. Since the latest version is a release candidate, in order to install it you have to pass the `--pre` flag to pip:

```
pip install --pre pydoop
```

S.

**Comment by mkobos** [comment]
Is it safe to use the release candidate or should we wait until the stable version comes out?

**Comment by simleo** [comment]
Although the RC has not been used in production yet, avroknife uses only the HDFS API. That part should be as stable as it is in the previous version

**Comment by mkobos** [comment]
Ok, I tried to install pydoop the way you descibed it, but I get the following error

```
adminuser@adminuser-VirtualBox:~/tmp$ sudo -i pip -v install --pre pydoop
Downloading/unpacking pydoop
  Using version 1.0.0-rc2 (newest of versions: 1.0.0-rc2, 1.0.0-rc1, 0.12.0, 0.11.1, 0.10.0, 0.10.0_rc1, 0.9.1, 0.9.0)
  Downloading pydoop-1.0.0-rc2.tar.gz (931kB): 
  Downloading from URL https://pypi.python.org/packages/source/p/pydoop/pydoop-1.0.0-rc2.tar.gz#md5=e73385876d4e921e85c2088a33767799 (from https://pypi.python.org/simple/pydoop/)
...Downloading pydoop-1.0.0-rc2.tar.gz (931kB): 931kB downloaded
  Running setup.py (path:/tmp/pip_build_root/pydoop/setup.py) egg_info for package pydoop
    using setuptools version 3.3
    running egg_info
    creating pip-egg-info/pydoop.egg-info
    writing requirements to pip-egg-info/pydoop.egg-info/requires.txt
    writing pip-egg-info/pydoop.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pydoop.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pydoop.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pydoop.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/pydoop.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*' found under directory 'examples/wordcount/c++'
    writing manifest file 'pip-egg-info/pydoop.egg-info/SOURCES.txt'
Installing collected packages: pydoop
  Running setup.py install for pydoop
    using setuptools version 3.3
    running install
    running build
    hdfs core implementation: native
    error: [Errno 2] No such file or directory
```

**Comment by mdrio** [comment]
Hi, I noticed you are trying to install pydoop on cdh4.7, which is not fully supported yet. I am trying to replicate the problem, I will give you more information soon.

**Comment by mkobos** [comment]
Thanks. Please note that Pydoop version 0.12 works fine with CDH4.7.

**Comment by mdrio** [comment]
Unfortunately I was not able to replicate your problem installing on a fresh ubuntu 14.04 cdh 4.7.0. 

Anyway I found out a dependency is not documented: python-dev
So, try to run:

sudo apt-get install python-dev
sudo apt-get install libssl-dev

and then:

sudo pip install --pre pydoop

Let me know if it works.

**Comment by mkobos** [comment]
@mdrio: I followed your advice and installed additionally `python-dev` but to no avail - I get the same exact error when running `sudo -i pip -v install --pre pydoop` (see the [previous comment](https://github.com/CeON/avroknife/pull/1#issuecomment-78246344)).

I also used a fresh ubuntu box (version 14.04.1, downloaded from https://virtualboximages.com/Ubuntu+14.04.01+amd64+Desktop+VirtualBox+VDI) and installed Hadoop and JDK following the description in the "Installation" section in [avroknife's README](https://github.com/CeON/avroknife/blob/master/README.markdown). Note that in order to install `pydoop`, I used `sudo` with `-i` switch and you didn't. I used this switch because otherwise pydoop installation complains that it cannot find `$JAVA_HOME`, namely:

```
File "pydoop/utils/jvm.py", line 28, in get_java_home

  raise RuntimeError("java home not found, try setting JAVA_HOME")
```

Here is a basic information about the configuration of my ubuntu box:

```
adminuser@adminuser-VirtualBox:~$ uname -a
Linux adminuser-VirtualBox 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
adminuser@adminuser-VirtualBox:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:    14.04
Codename:   trusty
adminuser@adminuser-VirtualBox:~$ java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

If you want, I can send you my Ubuntu VM image with Hadoop, Java, and mentioned Python packages installed on which the pydoop 1.0.0-rc2 installation fails.

**Comment by mdrio** [comment]
Yes, it will be great to have your VM, thank you very much.
It seems just a problem of how things are installed.
Ah, I used the command sudo -E to use the $user environment, I forgot to mention it, sorry.

**Comment by mkobos** [comment]
Unfortunatelly, neither does it work with the `-E` flag.

I sent the VM image to your crs4 mailbox using the wetransfer.com service.

**Comment by mdrio** [comment]
Ok, your VM helped us a lot.
We found a problem when git is not installed and it should be fixed. I put a temporary release here:
https://www.dropbox.com/s/iq4d0c04syporqc/pydoop-1.0.0rc2.tar.gz

I checked on your VM and it worked. To test it just run:
wget https://www.dropbox.com/s/iq4d0c04syporqc/pydoop-1.0.0rc2.tar.gz
sudo -E pip install pydoop-1.0.0rc2.tar.gz

**Comment by mkobos** [comment]
Thanks, this temporary release indeed gets installed without problems. 

Please let me know when it becomes available in the PyPI repostiory (possibly as a normal release, not a release candidate) so I can update the installation instructions in the README.

**Comment by mkobos** [comment]
BTW, I applied @simleo 's fix to the link to the Pydoop installation docs the in commit 5dd6ef64812a05d541ae8d707dd2b94852f9ef36

**Comment by simleo** [comment]
Hello,

Pydoop 1.0.0 is now available. You should be able to install it via `pip install pydoop`. Thanks for helping us test it!

Simone

**Comment by mkobos** [comment]
Thanks! 

Unfortunatelly, I noticed that part of HDFS-related tests from avroknife's testing suite stopped working after installing Pydoop 1.0.0 (I checked both 1.0.0 and 1.0.0-rc2 versions; there are no problems with version 0.12). I'm going to investigate further.

**Comment by mkobos** [comment]
I managed to fix the bug (see b620a3a15d2fcbfbddfc46088e32fff525ea20af). It turned out that after writing to a Pydoop HDFS file object returned from `hdfs.open()` call, I didn't close  it before exiting the program. In the previous version of Pydoop (0.12) this was Ok, but in the current one (1.0.0) this results in creation of an empty file.

**Pull request closed without merging**
